# Generated by Django 4.2.25 on 2025-10-29 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_hive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('offer', 'Offer'), ('need', 'Need')], max_length=10, verbose_name='service type')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed')], default='active', max_length=20, verbose_name='status')),
                ('estimated_hours', models.PositiveIntegerField(blank=True, help_text='Estimated time to complete this service', null=True, verbose_name='estimated hours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('message', models.TextField(blank=True, help_text='Optional message from requester', verbose_name='message')),
                ('response_note', models.TextField(blank=True, help_text="Owner's response to the request", verbose_name='response note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL, verbose_name='requester')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='the_hive.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'service request',
                'verbose_name_plural': 'service requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='tag name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='the_hive_ta_slug_2ea6be_idx'), models.Index(fields=['created_at'], name='the_hive_ta_created_017f39_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_start', models.DateTimeField(verbose_name='scheduled start time')),
                ('scheduled_end', models.DateTimeField(verbose_name='scheduled end time')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='actual start time')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='actual end time')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='session notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='the_hive.servicerequest', verbose_name='service request')),
            ],
            options={
                'verbose_name': 'service session',
                'verbose_name_plural': 'service sessions',
                'ordering': ['scheduled_start'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='services', to='the_hive.tag', verbose_name='tags'),
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('disputed', 'Disputed')], default='pending', max_length=20, verbose_name='status')),
                ('completion_notes', models.TextField(blank=True, verbose_name='completion notes')),
                ('time_transferred', models.BooleanField(default=False, help_text='Whether time has been transferred in the time banking system', verbose_name='time transferred')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmed at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_completions', to=settings.AUTH_USER_MODEL, verbose_name='marked by')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion', to='the_hive.servicesession', verbose_name='session')),
            ],
            options={
                'verbose_name': 'completion',
                'verbose_name_plural': 'completions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='servicesession',
            index=models.Index(fields=['service_request'], name='the_hive_se_service_1f4270_idx'),
        ),
        migrations.AddIndex(
            model_name='servicesession',
            index=models.Index(fields=['status'], name='the_hive_se_status_a7ba33_idx'),
        ),
        migrations.AddIndex(
            model_name='servicesession',
            index=models.Index(fields=['scheduled_start'], name='the_hive_se_schedul_d618c3_idx'),
        ),
        migrations.AddIndex(
            model_name='servicesession',
            index=models.Index(fields=['actual_start'], name='the_hive_se_actual__fd22a4_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['requester'], name='the_hive_se_request_1a5b0f_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['service'], name='the_hive_se_service_768d05_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status'], name='the_hive_se_status_7a22a7_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['created_at'], name='the_hive_se_created_28a2fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicerequest',
            unique_together={('requester', 'service')},
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['owner'], name='the_hive_se_owner_i_758d06_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['service_type'], name='the_hive_se_service_eb2011_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['status'], name='the_hive_se_status_b29b83_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['created_at'], name='the_hive_se_created_0f2d1c_idx'),
        ),
        migrations.AddIndex(
            model_name='completion',
            index=models.Index(fields=['session'], name='the_hive_co_session_0c26e0_idx'),
        ),
        migrations.AddIndex(
            model_name='completion',
            index=models.Index(fields=['marked_by'], name='the_hive_co_marked__73a16b_idx'),
        ),
        migrations.AddIndex(
            model_name='completion',
            index=models.Index(fields=['status'], name='the_hive_co_status_afe59a_idx'),
        ),
        migrations.AddIndex(
            model_name='completion',
            index=models.Index(fields=['time_transferred'], name='the_hive_co_time_tr_1bd967_idx'),
        ),
        migrations.AddIndex(
            model_name='completion',
            index=models.Index(fields=['created_at'], name='the_hive_co_created_d22c58_idx'),
        ),
    ]
