# Generated by Django 4.2.25 on 2025-10-29 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_hive', '0002_service_servicerequest_tag_servicesession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current time balance in hours', max_digits=8, verbose_name='balance (hours)')),
                ('total_earned', models.DecimalField(decimal_places=2, default=0.0, help_text='Total hours earned by providing services', max_digits=10, verbose_name='total earned (hours)')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, help_text='Total hours spent on receiving services', max_digits=10, verbose_name='total spent (hours)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_account', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'time account',
                'verbose_name_plural': 'time accounts',
            },
        ),
        migrations.CreateModel(
            name='TimeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('adjustment', 'Adjustment'), ('bonus', 'Bonus')], max_length=20, verbose_name='transaction type')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in hours (always positive)', max_digits=6, verbose_name='amount (hours)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='status')),
                ('description', models.CharField(help_text='Description of the transaction', max_length=500, verbose_name='description')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='the_hive.timeaccount', verbose_name='account')),
                ('processed_by', models.ForeignKey(blank=True, help_text='User or admin who processed this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_transactions', to=settings.AUTH_USER_MODEL, verbose_name='processed by')),
                ('related_completion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_transactions', to='the_hive.completion', verbose_name='related completion')),
                ('related_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_transactions', to='the_hive.service', verbose_name='related service')),
                ('related_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_transactions', to='the_hive.servicesession', verbose_name='related session')),
            ],
            options={
                'verbose_name': 'time transaction',
                'verbose_name_plural': 'time transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account'], name='the_hive_ti_account_ece727_idx'), models.Index(fields=['transaction_type'], name='the_hive_ti_transac_15f43e_idx'), models.Index(fields=['status'], name='the_hive_ti_status_4f6a7f_idx'), models.Index(fields=['related_service'], name='the_hive_ti_related_eb6392_idx'), models.Index(fields=['related_session'], name='the_hive_ti_related_487622_idx'), models.Index(fields=['created_at'], name='the_hive_ti_created_2c2125_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='timeaccount',
            index=models.Index(fields=['user'], name='the_hive_ti_user_id_d6b483_idx'),
        ),
        migrations.AddIndex(
            model_name='timeaccount',
            index=models.Index(fields=['balance'], name='the_hive_ti_balance_83f682_idx'),
        ),
        migrations.AddIndex(
            model_name='timeaccount',
            index=models.Index(fields=['created_at'], name='the_hive_ti_created_cf4a50_idx'),
        ),
    ]
