# Generated by Django 4.2.25 on 2025-10-30 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_hive', '0003_timeaccount_timetransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional conversation title', max_length=200, verbose_name='title')),
                ('is_archived', models.BooleanField(default=False, help_text='Whether this conversation is archived', verbose_name='is archived')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(help_text='Users participating in this conversation', related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='participants')),
                ('related_service', models.ForeignKey(blank=True, help_text='Optional service this conversation is about', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='the_hive.service', verbose_name='related service')),
            ],
            options={
                'verbose_name': 'conversation',
                'verbose_name_plural': 'conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='The message content', verbose_name='message body')),
                ('is_read', models.BooleanField(default=False, help_text='Whether this message has been read by recipients', verbose_name='is read')),
                ('read_at', models.DateTimeField(blank=True, help_text='When this message was first read', null=True, verbose_name='read at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='the_hive.conversation', verbose_name='conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['conversation'], name='the_hive_me_convers_aca4ee_idx'), models.Index(fields=['sender'], name='the_hive_me_sender__ad6728_idx'), models.Index(fields=['is_read'], name='the_hive_me_is_read_afae9a_idx'), models.Index(fields=['created_at'], name='the_hive_me_created_be78dd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['related_service'], name='the_hive_co_related_1a6893_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['is_archived'], name='the_hive_co_is_arch_28f19d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['created_at'], name='the_hive_co_created_d21a63_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['updated_at'], name='the_hive_co_updated_bbcf99_idx'),
        ),
    ]
