# Generated by Django 4.2.25 on 2025-10-30 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_hive', '0004_conversation_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Thread title', max_length=200, verbose_name='title')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pinned', 'Pinned')], default='open', max_length=20, verbose_name='status')),
                ('is_flagged', models.BooleanField(default=False, help_text='Whether this thread has been flagged for moderation', verbose_name='is flagged')),
                ('flagged_reason', models.TextField(blank=True, help_text='Reason why this thread was flagged', verbose_name='flagged reason')),
                ('flagged_at', models.DateTimeField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Number of times this thread has been viewed', verbose_name='views count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_threads', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_threads', to=settings.AUTH_USER_MODEL, verbose_name='flagged by')),
                ('related_service', models.ForeignKey(blank=True, help_text='Optional service this thread is about', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_threads', to='the_hive.service', verbose_name='related service')),
                ('tags', models.ManyToManyField(blank=True, related_name='threads', to='the_hive.tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'thread',
                'verbose_name_plural': 'threads',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ThankYouNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Personal thank you message', verbose_name='thank you message')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('read', 'Read'), ('archived', 'Archived')], default='sent', max_length=20, verbose_name='status')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_thank_you_notes', to=settings.AUTH_USER_MODEL, verbose_name='from user')),
                ('related_service', models.ForeignKey(blank=True, help_text='Service this thank you note is about', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thank_you_notes', to='the_hive.service', verbose_name='related service')),
                ('related_session', models.ForeignKey(blank=True, help_text='Session this thank you note is about', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thank_you_notes', to='the_hive.servicesession', verbose_name='related session')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_thank_you_notes', to=settings.AUTH_USER_MODEL, verbose_name='to user')),
            ],
            options={
                'verbose_name': 'thank you note',
                'verbose_name_plural': 'thank you notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='The post content', verbose_name='post body')),
                ('status', models.CharField(choices=[('published', 'Published'), ('hidden', 'Hidden'), ('flagged', 'Flagged')], default='published', max_length=20, verbose_name='status')),
                ('is_flagged', models.BooleanField(default=False, help_text='Whether this post has been flagged for moderation', verbose_name='is flagged')),
                ('flagged_reason', models.TextField(blank=True, help_text='Reason why this post was flagged', verbose_name='flagged reason')),
                ('flagged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_posts', to=settings.AUTH_USER_MODEL, verbose_name='flagged by')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='the_hive.thread', verbose_name='thread')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['author'], name='the_hive_th_author__3427ca_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['status'], name='the_hive_th_status_9d8d6a_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['is_flagged'], name='the_hive_th_is_flag_fce519_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['related_service'], name='the_hive_th_related_00bad3_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['created_at'], name='the_hive_th_created_4d73bd_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['updated_at'], name='the_hive_th_updated_74a304_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['views_count'], name='the_hive_th_views_c_62b851_idx'),
        ),
        migrations.AddIndex(
            model_name='thankyounote',
            index=models.Index(fields=['from_user'], name='the_hive_th_from_us_82f197_idx'),
        ),
        migrations.AddIndex(
            model_name='thankyounote',
            index=models.Index(fields=['to_user'], name='the_hive_th_to_user_39997c_idx'),
        ),
        migrations.AddIndex(
            model_name='thankyounote',
            index=models.Index(fields=['status'], name='the_hive_th_status_174288_idx'),
        ),
        migrations.AddIndex(
            model_name='thankyounote',
            index=models.Index(fields=['related_service'], name='the_hive_th_related_e9b4c3_idx'),
        ),
        migrations.AddIndex(
            model_name='thankyounote',
            index=models.Index(fields=['related_session'], name='the_hive_th_related_d22929_idx'),
        ),
        migrations.AddIndex(
            model_name='thankyounote',
            index=models.Index(fields=['created_at'], name='the_hive_th_created_7cf90c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='thankyounote',
            unique_together={('from_user', 'to_user', 'related_service')},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['thread'], name='the_hive_po_thread__18c2e7_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author'], name='the_hive_po_author__1195e0_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status'], name='the_hive_po_status_60068f_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_flagged'], name='the_hive_po_is_flag_e1a41a_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at'], name='the_hive_po_created_ee79d9_idx'),
        ),
    ]
