# Generated by Django 4.2.25 on 2025-10-30 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('the_hive', '0005_thread_thankyounote_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='object id')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Inappropriate Content'), ('harassment', 'Harassment'), ('fraud', 'Fraud/Scam'), ('violence', 'Violence/Threats'), ('copyright', 'Copyright Violation'), ('misinformation', 'Misinformation'), ('other', 'Other')], help_text='Primary reason for this report', max_length=20, verbose_name='reason')),
                ('description', models.TextField(help_text='Detailed description of the issue', verbose_name='description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('escalated', 'Escalated')], default='pending', max_length=20, verbose_name='status')),
                ('reporter_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the reporter for tracking', null=True, verbose_name='reporter IP')),
                ('evidence_url', models.URLField(blank=True, help_text='Optional link to additional evidence', verbose_name='evidence URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL, verbose_name='reporter')),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('warning_issued', 'Warning Issued'), ('content_hidden', 'Content Hidden'), ('content_removed', 'Content Removed'), ('user_suspended', 'User Suspended'), ('user_banned', 'User Banned'), ('resolved', 'Report Resolved'), ('dismissed', 'Report Dismissed'), ('escalated', 'Escalated to Admin'), ('reinstated', 'Content Reinstated'), ('other', 'Other Action')], help_text='Type of moderation action taken', max_length=30, verbose_name='action')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Severity level of this action', max_length=20, verbose_name='severity')),
                ('notes', models.TextField(help_text='Detailed notes about the action taken', verbose_name='notes')),
                ('duration_days', models.PositiveIntegerField(blank=True, help_text='Duration for temporary actions (suspensions, etc.)', null=True, verbose_name='duration in days')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this action expires (for temporary actions)', null=True, verbose_name='expires at')),
                ('is_reversed', models.BooleanField(default=False, help_text='Whether this action has been reversed', verbose_name='is reversed')),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True, help_text='Reason for reversing this action', verbose_name='reversal reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_user', models.ForeignKey(blank=True, help_text='User who is affected by this moderation action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions_received', to=settings.AUTH_USER_MODEL, verbose_name='affected user')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL, verbose_name='moderator')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to='the_hive.report', verbose_name='related report')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_moderation_actions', to=settings.AUTH_USER_MODEL, verbose_name='reversed by')),
            ],
            options={
                'verbose_name': 'moderation action',
                'verbose_name_plural': 'moderation actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reporter'], name='the_hive_re_reporte_1cbdfd_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['content_type', 'object_id'], name='the_hive_re_content_d2e31b_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reason'], name='the_hive_re_reason_ebb94c_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='the_hive_re_status_ee86ee_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='the_hive_re_created_064e14_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('reporter', 'content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['report'], name='the_hive_mo_report__ab46a1_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['moderator'], name='the_hive_mo_moderat_a8f0da_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['affected_user'], name='the_hive_mo_affecte_9a0c84_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['action'], name='the_hive_mo_action_263993_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['severity'], name='the_hive_mo_severit_e22233_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['is_reversed'], name='the_hive_mo_is_reve_f297c3_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['created_at'], name='the_hive_mo_created_69f49a_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['expires_at'], name='the_hive_mo_expires_d3fc5b_idx'),
        ),
    ]
