# Generated by Django 4.2.25 on 2025-10-30 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_hive', '0006_report_moderationaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('service_request', 'Service Request'), ('service_accepted', 'Service Accepted'), ('service_rejected', 'Service Rejected'), ('service_completed', 'Service Completed'), ('session_scheduled', 'Session Scheduled'), ('session_reminder', 'Session Reminder'), ('time_credited', 'Time Credited'), ('time_debited', 'Time Debited'), ('time_bonus', 'Time Bonus'), ('low_balance', 'Low Balance Warning'), ('new_message', 'New Message'), ('conversation_invite', 'Conversation Invite'), ('thank_you_received', 'Thank You Note Received'), ('thread_reply', 'Thread Reply'), ('thread_mention', 'Thread Mention'), ('post_liked', 'Post Liked'), ('content_flagged', 'Content Flagged'), ('moderation_action', 'Moderation Action'), ('report_resolved', 'Report Resolved'), ('system_announcement', 'System Announcement'), ('maintenance_notice', 'Maintenance Notice'), ('policy_update', 'Policy Update'), ('account_warning', 'Account Warning'), ('new_member', 'New Community Member'), ('milestone_reached', 'Milestone Reached'), ('community_event', 'Community Event')], help_text='Type of notification', max_length=30, verbose_name='notification type')),
                ('title', models.CharField(help_text='Short notification title', max_length=200, verbose_name='title')),
                ('message', models.TextField(help_text='Detailed notification message', verbose_name='message')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', help_text='Priority level of this notification', max_length=10, verbose_name='priority')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Additional data related to this notification', verbose_name='payload')),
                ('is_read', models.BooleanField(default=False, help_text='Whether this notification has been read', verbose_name='is read')),
                ('read_at', models.DateTimeField(blank=True, help_text='When this notification was read', null=True, verbose_name='read at')),
                ('is_dismissed', models.BooleanField(default=False, help_text='Whether this notification has been dismissed', verbose_name='is dismissed')),
                ('dismissed_at', models.DateTimeField(blank=True, null=True, verbose_name='dismissed at')),
                ('is_sent', models.BooleanField(default=False, help_text='Whether this notification has been sent via external channels', verbose_name='is sent')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('delivery_channels', models.JSONField(blank=True, default=list, help_text='Channels used to deliver this notification (email, push, etc.)', verbose_name='delivery channels')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this notification expires and should be hidden', null=True, verbose_name='expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='the_hive.conversation', verbose_name='related conversation')),
                ('related_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='the_hive.service', verbose_name='related service')),
                ('related_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='the_hive.thread', verbose_name='related thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='the_hive_no_user_id_440dd1_idx'), models.Index(fields=['notification_type'], name='the_hive_no_notific_22f7bf_idx'), models.Index(fields=['priority'], name='the_hive_no_priorit_56a39b_idx'), models.Index(fields=['is_read'], name='the_hive_no_is_read_c1a449_idx'), models.Index(fields=['is_dismissed'], name='the_hive_no_is_dism_12f156_idx'), models.Index(fields=['is_sent'], name='the_hive_no_is_sent_90819c_idx'), models.Index(fields=['created_at'], name='the_hive_no_created_62849f_idx'), models.Index(fields=['expires_at'], name='the_hive_no_expires_7c8af6_idx'), models.Index(fields=['user', 'is_read'], name='the_hive_no_user_id_77887a_idx')],
            },
        ),
    ]
