# Generated by Django 4.2.25 on 2025-10-30 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_hive', '0007_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('service_provider', 'Service Provider Review'), ('service_receiver', 'Service Receiver Review'), ('service_quality', 'Service Quality Review')], help_text='Type of review - provider, receiver, or service quality', max_length=20, verbose_name='review type')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], help_text='Rating from 1 (poor) to 5 (excellent)', verbose_name='rating')),
                ('title', models.CharField(help_text='Short title summarizing the review', max_length=200, verbose_name='review title')),
                ('content', models.TextField(help_text='Detailed review content', verbose_name='review content')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Whether this review should be shown anonymously', verbose_name='is anonymous')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this review has been verified by the system', verbose_name='is verified')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this review should be featured prominently', verbose_name='is featured')),
                ('helpful_count', models.PositiveIntegerField(default=0, help_text='Number of users who found this review helpful', verbose_name='helpful count')),
                ('report_count', models.PositiveIntegerField(default=0, help_text='Number of times this review has been reported', verbose_name='report count')),
                ('is_published', models.BooleanField(default=True, help_text='Whether this review is visible to others', verbose_name='is published')),
                ('is_flagged', models.BooleanField(default=False, help_text='Whether this review has been flagged for moderation', verbose_name='is flagged')),
                ('moderation_notes', models.TextField(blank=True, help_text='Internal notes for moderators', verbose_name='moderation notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('related_completion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='the_hive.completion', verbose_name='related completion')),
                ('related_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='the_hive.service', verbose_name='related service')),
                ('related_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='the_hive.servicesession', verbose_name='related session')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL, verbose_name='reviewee')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='reviewer')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating across all review types', max_digits=3, verbose_name='overall rating')),
                ('overall_review_count', models.PositiveIntegerField(default=0, verbose_name='overall review count')),
                ('provider_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating as a service provider', max_digits=3, verbose_name='provider rating')),
                ('provider_review_count', models.PositiveIntegerField(default=0, verbose_name='provider review count')),
                ('receiver_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating as a service receiver', max_digits=3, verbose_name='receiver rating')),
                ('receiver_review_count', models.PositiveIntegerField(default=0, verbose_name='receiver review count')),
                ('service_quality_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating for service quality', max_digits=3, verbose_name='service quality rating')),
                ('service_quality_review_count', models.PositiveIntegerField(default=0, verbose_name='service quality review count')),
                ('rating_distribution', models.JSONField(default=dict, help_text='Distribution of ratings (1-5 stars)', verbose_name='rating distribution')),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='last reviewed at')),
                ('is_verified_reviewer', models.BooleanField(default=False, help_text='Whether user is a verified/trusted reviewer', verbose_name='is verified reviewer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_summary', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user rating summary',
                'verbose_name_plural': 'user rating summaries',
                'indexes': [models.Index(fields=['overall_rating'], name='the_hive_us_overall_28d882_idx'), models.Index(fields=['provider_rating'], name='the_hive_us_provide_3880c1_idx'), models.Index(fields=['receiver_rating'], name='the_hive_us_receive_dfec22_idx'), models.Index(fields=['overall_review_count'], name='the_hive_us_overall_d799d7_idx'), models.Index(fields=['last_reviewed_at'], name='the_hive_us_last_re_68404b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpfulVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='the_hive.review', verbose_name='review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'review helpful vote',
                'verbose_name_plural': 'review helpful votes',
                'indexes': [models.Index(fields=['review'], name='the_hive_re_review__cd3eca_idx'), models.Index(fields=['user'], name='the_hive_re_user_id_56d63f_idx'), models.Index(fields=['created_at'], name='the_hive_re_created_56a0f5_idx')],
                'unique_together': {('review', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewer'], name='the_hive_re_reviewe_9ca067_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewee'], name='the_hive_re_reviewe_d1c289_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['related_service'], name='the_hive_re_related_b39103_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['review_type'], name='the_hive_re_review__e9b7fb_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='the_hive_re_rating_6b3c36_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_published'], name='the_hive_re_is_publ_3eb2b5_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_flagged'], name='the_hive_re_is_flag_475168_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['helpful_count'], name='the_hive_re_helpful_8e783e_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='the_hive_re_created_740dc8_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['published_at'], name='the_hive_re_publish_c7ef6d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('reviewer', 'reviewee', 'related_service', 'review_type')},
        ),
    ]
