# Generated by Django 4.2.25 on 2025-11-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hive', '0008_review_userrating_reviewhelpfulvote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='address',
            field=models.TextField(blank=True, help_text='Human-readable address for this service location', null=True, verbose_name='address'),
        ),
    ]
