# Generated by Django 4.2.5 on 2025-11-26 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_hive', '0009_service_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='discussion_thread',
            field=models.OneToOneField(blank=True, help_text='Public discussion thread for this service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_discussion', to='the_hive.thread', verbose_name='discussion thread'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual hours worked (can be updated after completion)', max_digits=6, null=True, verbose_name='actual hours'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='actual_hours_owner_approved',
            field=models.BooleanField(default=False, help_text='Service owner has approved the actual hours', verbose_name='owner approved hours'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='actual_hours_requester_approved',
            field=models.BooleanField(default=False, help_text='Requester has approved the actual hours', verbose_name='requester approved hours'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='conversation',
            field=models.OneToOneField(blank=True, help_text='Private conversation between requester and owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_request', to='the_hive.conversation', verbose_name='conversation'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='owner_approved',
            field=models.BooleanField(default=False, help_text='Service owner has approved to start', verbose_name='owner approved'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='requester_approved',
            field=models.BooleanField(default=False, help_text='Requester has approved to start', verbose_name='requester approved'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status'),
        ),
    ]
