# Generated by Django 4.2.25 on 2025-12-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hive', '0010_service_discussion_thread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='wikidata_id',
            field=models.CharField(blank=True, help_text='Wikidata Q identifier (e.g., Q12345)', max_length=20, null=True, verbose_name='wikidata id'),
        ),
        migrations.AddField(
            model_name='tag',
            name='wikidata_url',
            field=models.URLField(blank=True, help_text='Full URL to Wikidata page', null=True, verbose_name='wikidata url'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['wikidata_id'], name='the_hive_ta_wikidat_89fe3d_idx'),
        ),
    ]
