# Generated by Django 4.2.25 on 2025-12-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hive', '0011_add_wikidata_to_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='avatars/', verbose_name='avatar'),
        ),
    ]
