# Generated by Django 4.2.25 on 2025-12-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hive', '0012_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ban_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the ban expires (null for permanent ban)', null=True, verbose_name='ban expires at'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ban_reason',
            field=models.TextField(blank=True, help_text='Reason for the ban', verbose_name='ban reason'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_banned',
            field=models.BooleanField(default=False, help_text='Whether this user is banned from the platform', verbose_name='is banned'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='Whether this user is temporarily suspended', verbose_name='is suspended'),
        ),
        migrations.AddField(
            model_name='profile',
            name='suspension_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the suspension expires', null=True, verbose_name='suspension expires at'),
        ),
        migrations.AddField(
            model_name='profile',
            name='suspension_reason',
            field=models.TextField(blank=True, help_text='Reason for the suspension', verbose_name='suspension reason'),
        ),
    ]
