# Generated by Django 4.2.25 on 2025-12-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hive', '0013_profile_ban_expires_at_profile_ban_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for this service', null=True, upload_to='service_images/', verbose_name='service image'),
        ),
    ]
