# Generated by Django 4.2.25 on 2025-12-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hive', '0014_add_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='owner_completed',
            field=models.BooleanField(default=False, help_text='Service owner has marked the service as completed', verbose_name='owner completed'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='requester_completed',
            field=models.BooleanField(default=False, help_text='Requester has marked the service as completed', verbose_name='requester completed'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='actual_hours_owner_approved',
            field=models.BooleanField(default=False, help_text='Service owner has approved the actual hours (deprecated)', verbose_name='owner approved hours'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='actual_hours_requester_approved',
            field=models.BooleanField(default=False, help_text='Requester has approved the actual hours (deprecated)', verbose_name='requester approved hours'),
        ),
    ]
