# Generated by Django 4.2.25 on 2025-12-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_hive', '0015_servicerequest_owner_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='capacity',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of participants for this service (e.g., for group classes)', verbose_name='capacity'),
        ),
    ]
